development:
  adapter: postgresql
  encoding: unicode
  database: sport_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sport_test
  pool: 5
  username: postgres
  password:
  host: localhost

#production:
#  adapter: postgresql
#  encoding: unicode
#  database: blog_production
#  pool: 5
#  username: postgres
#  password:
